import {
  Invoice,
  Contract,
  GuardDeployment,
  PostOrder,
  IncidentAlert,
} from '@/types';

// Mock Guards Telemetry
export const MOCK_GUARDS: GuardDeployment[] = [
  {
    id: 'grd-01',
    badgeNumber: 'LSF-CPO-104',
    fullName: 'Alexander Cruz',
    callsign: 'VANGUARD-1',
    rank: 'CPO_SPECIALIST',
    assignedSite: 'Aegis Global HQ - Executive Suite',
    postLocation: 'Sector 4A - North Perimeter Gate',
    coordinates: { lat: 37.7749, lng: -122.4194 },
    shiftStart: '06:00 UTC',
    shiftEnd: '18:00 UTC',
    status: 'ACTIVE',
    armed: true,
    biometricHeartRate: 74,
    radioFrequencyMhz: '462.5625',
    lastCheckinTime: '2 mins ago',
  },
  {
    id: 'grd-02',
    badgeNumber: 'LSF-TAC-882',
    fullName: 'Dmitri Volkov',
    callsign: 'IRON-SHIELD',
    rank: 'TACTICAL_LEAD',
    assignedSite: 'NexaCorp Data Fortress',
    postLocation: 'Server Vault Level -2',
    coordinates: { lat: 37.7833, lng: -122.4167 },
    shiftStart: '08:00 UTC',
    shiftEnd: '20:00 UTC',
    status: 'ACTIVE',
    armed: true,
    biometricHeartRate: 82,
    radioFrequencyMhz: '467.6375',
    lastCheckinTime: '4 mins ago',
  },
  {
    id: 'grd-03',
    badgeNumber: 'LSF-SRV-309',
    fullName: 'Sarah Chen',
    callsign: 'HAWK-EYE',
    rank: 'SURVEILLANCE_TECH',
    assignedSite: 'Meridian Terminal Convoy',
    postLocation: 'Mobile Escort Unit 03',
    coordinates: { lat: 37.769, lng: -122.446 },
    shiftStart: '10:00 UTC',
    shiftEnd: '22:00 UTC',
    status: 'ENGAGED',
    armed: false,
    biometricHeartRate: 98,
    radioFrequencyMhz: '462.6125',
    lastCheckinTime: 'Just now',
  },
  {
    id: 'grd-04',
    badgeNumber: 'LSF-CPO-441',
    fullName: 'Mateo Morales',
    callsign: 'GHOST-ACTUAL',
    rank: 'FIELD_OPERATOR',
    assignedSite: 'Sovereign Bank Vault',
    postLocation: 'Sub-Level Gate 1',
    coordinates: { lat: 37.791, lng: -122.398 },
    shiftStart: '12:00 UTC',
    shiftEnd: '00:00 UTC',
    status: 'STANDBY',
    armed: true,
    biometricHeartRate: 68,
    radioFrequencyMhz: '467.5875',
    lastCheckinTime: '8 mins ago',
  },
];

// Mock Invoices Ledger
export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'inv-001',
    invoiceNumber: 'LSF-INV-2026-0891',
    clientId: 'cli-001',
    clientName: 'Elena Rostova',
    clientOrganization: 'Aegis Holdings International',
    clientEmail: 'e.rostova@aegis-corp.global',
    billingAddress: '555 Mission St, Suite 3200, San Francisco, CA',
    status: 'OVERDUE',
    issueDate: '2026-08-15',
    dueDate: '2026-09-01',
    currency: 'USD',
    subtotal: 48500,
    taxTotal: 4001.25,
    discount: 0,
    totalAmount: 52501.25,
    paymentTerms: 'NET_15',
    notes: 'Escort details for European delegation summits & armored motorcade.',
    lineItems: [
      {
        id: 'li-01',
        description: 'Tier-1 Close Protection Officers (2x Operators - 120 hrs)',
        unit: 'HOURS',
        quantity: 120,
        unitRate: 250,
        taxRate: 0.0825,
        total: 30000,
        serviceCategory: 'EXECUTIVE_PROTECTION',
      },
      {
        id: 'li-02',
        description: 'B6 Armored Suburban Escort & Counter-Surveillance Driver',
        unit: 'DAYS',
        quantity: 5,
        unitRate: 2500,
        taxRate: 0.0825,
        total: 12500,
        serviceCategory: 'ARMORED_CONVOY',
      },
      {
        id: 'li-03',
        description: 'Technical Surveillance Countermeasures (TSCM Room Sweep)',
        unit: 'FLAT_FEE',
        quantity: 1,
        unitRate: 6000,
        taxRate: 0.0825,
        total: 6000,
        serviceCategory: 'SURVEILLANCE_COUNTERMEASURES',
      },
    ],
  },
  {
    id: 'inv-002',
    invoiceNumber: 'LSF-INV-2026-0904',
    clientId: 'cli-002',
    clientName: 'Julian Sterling',
    clientOrganization: 'Sterling Biotech Labs',
    clientEmail: 'j.sterling@sterling-bio.com',
    billingAddress: '100 Innovation Way, Cambridge, MA',
    status: 'PENDING',
    issueDate: '2026-09-12',
    dueDate: '2026-09-27',
    currency: 'USD',
    subtotal: 82000,
    taxTotal: 6765,
    discount: 2000,
    totalAmount: 86765,
    paymentTerms: 'NET_15',
    notes: 'High-containment biolab static post security & biometric access control.',
    lineItems: [
      {
        id: 'li-04',
        description: '24/7 Armed Static Guard Post - Biosafety Level 4 Facility',
        unit: 'HOURS',
        quantity: 360,
        unitRate: 180,
        taxRate: 0.0825,
        total: 64800,
        serviceCategory: 'STATIC_POST',
      },
      {
        id: 'li-05',
        description: 'K9 Explosive & Contraband Detection Team',
        unit: 'DAYS',
        quantity: 10,
        unitRate: 1720,
        taxRate: 0.0825,
        total: 17200,
        serviceCategory: 'K9_UNIT',
      },
    ],
  },
  {
    id: 'inv-003',
    invoiceNumber: 'LSF-INV-2026-0915',
    clientId: 'cli-003',
    clientName: 'Victor Zhao',
    clientOrganization: 'Apex Quantum Technologies',
    clientEmail: 'v.zhao@apex-quantum.io',
    billingAddress: '400 Cyberway Blvd, Austin, TX',
    status: 'PAID',
    issueDate: '2026-09-01',
    dueDate: '2026-09-16',
    paidDate: '2026-09-10',
    currency: 'USD',
    subtotal: 115000,
    taxTotal: 9487.5,
    discount: 5000,
    totalAmount: 119487.5,
    paymentTerms: 'NET_15',
    notes: 'Paid via Wire Transfer (Ref #WT-APEX-998124). Fully settled.',
    lineItems: [
      {
        id: 'li-06',
        description: 'Quarterly Critical Infrastructure Defensive Grid Operation',
        unit: 'FLAT_FEE',
        quantity: 1,
        unitRate: 115000,
        taxRate: 0.0825,
        total: 115000,
        serviceCategory: 'EXECUTIVE_PROTECTION',
      },
    ],
  },
];

// Mock Contracts
export const MOCK_CONTRACTS: Contract[] = [
  {
    id: 'ctr-101',
    contractCode: 'LSF-CTR-2026-904',
    title: 'Master Defense & Close Protection Services Agreement',
    clientId: 'cli-001',
    clientName: 'Elena Rostova',
    clientCompany: 'Aegis Holdings International',
    status: 'ACTIVE',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    monthlyRetainer: 45000,
    totalContractValue: 540000,
    armedEscortAuthorized: true,
    ndaAttached: true,
    liabilityCoverageUSD: 10000000,
    eSignatureStatus: {
      clientSigned: true,
      clientSignerName: 'Elena Rostova (CEO)',
      clientSignedAt: '2026-01-02 14:22:10 UTC',
      docusignEnvelopeId: 'DS-9801-B782-99F12',
      securityDirectorSigned: true,
      securityDirectorSignedAt: '2026-01-02 15:01:45 UTC',
      ipAuditTrail: '192.0.2.148 (Verified via DocuSign AES)',
    },
    rateCards: [
      {
        id: 'rc-1',
        roleTitle: 'Senior Close Protection Officer (CPO)',
        standardRatePerHour: 250,
        hazardRatePerHour: 375,
        holidayRatePerHour: 500,
        minShiftHours: 8,
      },
      {
        id: 'rc-2',
        roleTitle: 'Tactical Driver & Armored Convoy Lead',
        standardRatePerHour: 200,
        hazardRatePerHour: 300,
        holidayRatePerHour: 400,
        minShiftHours: 8,
      },
    ],
    clauses: [
      {
        id: 'cl-1',
        section: '1.0',
        title: 'Rules of Engagement & Force Escalation',
        content: 'Contractor personnel are authorized to exercise defensive measures strictly in alignment with state jurisdictional law, proportional to immediate imminent threats to client life.',
        isMandatory: true,
        isEditable: false,
      },
      {
        id: 'cl-2',
        section: '2.0',
        title: 'Non-Disclosure & High-Security Confidentiality',
        content: 'All travel itineraries, communications, personal habits, and operational telemetry remain classified Top Secret under strict perpetual NDA penalty of $5,000,000 per violation.',
        isMandatory: true,
        isEditable: false,
      },
      {
        id: 'cl-3',
        section: '3.0',
        title: 'Emergency Medical & Tactical Extraction Protocols',
        content: 'Contractor guarantees a secondary rotary-wing or armored ground egress vehicle stationed within 15 minutes of primary principal coordinate at all times.',
        isMandatory: false,
        isEditable: true,
      },
    ],
  },
];

// Mock Post Orders
export const MOCK_POST_ORDERS: PostOrder[] = [
  {
    id: 'po-01',
    orderNumber: 'PO-2026-A1',
    siteName: 'Aegis Global HQ - Perimeter Alpha',
    threatLevel: 'NORMAL',
    effectiveDate: '2026-09-01',
    primaryDirectives: [
      'Maintain 100% biometric access control on Gate Alpha and Bravo.',
      'Conduct 30-minute sweeps of external perimeter with optical night-vision.',
      'Log and verify all incoming armored deliveries against master dispatch ledger.',
    ],
    restrictedZones: ['Server Vault Level -2', 'Executive Penthouse C', 'Armory Unit 4'],
    emergencyContactProtocol: 'Direct encrypted radio hail on Channel 4; notify Ops Center within 30 seconds of alert breach.',
    authorizedVisitorList: ['Marcus Vance', 'Elena Rostova', 'Dr. Aris Thorne', 'Dmitri Volkov'],
    assignedOfficersCount: 8,
    status: 'ACTIVE',
  },
  {
    id: 'po-02',
    orderNumber: 'PO-2026-B3',
    siteName: 'NexaCorp Quantum Research Lab',
    threatLevel: 'ELEVATED',
    effectiveDate: '2026-09-15',
    primaryDirectives: [
      'No unescorted personnel allowed within 50 meters of Quantum Core Chamber.',
      'Immediate lockdown on RF jam detection or unverified optical camera blind spots.',
    ],
    restrictedZones: ['Chamber 01', 'RF Faraday Cage', 'Cryo Storage'],
    emergencyContactProtocol: 'Activate silent panic strobe; dispatch rapid tactical backup from Sector 9.',
    authorizedVisitorList: ['Dr. Julian Sterling', 'Alexander Cruz'],
    assignedOfficersCount: 6,
    status: 'ACTIVE',
  },
];

// Mock Incident Alerts
export const MOCK_INCIDENTS: IncidentAlert[] = [
  {
    id: 'inc-01',
    timestamp: '2026-09-26 10:14:02 UTC',
    severity: 'WARNING',
    location: 'Perimeter West - Gate 4',
    title: 'Unidentified Drone Detected',
    description: 'Acoustic sensor picked up unauthorized micro-UAV loitering at 120ft altitude. RF jammer dispatched.',
    resolved: false,
    acknowledgedBy: 'IRON-SHIELD',
  },
  {
    id: 'inc-02',
    timestamp: '2026-09-26 08:30:19 UTC',
    severity: 'INFO',
    location: 'Executive Convoy - Route 101',
    title: 'Routine Motorcade Checkpoint Cleared',
    description: 'Convoy Bravo successfully crossed Waypoint Hotel with zero surveillance tail.',
    resolved: true,
    acknowledgedBy: 'VANGUARD-1',
  },
];

// Simulated Network Latency Helper (Mandate 21)
export async function simulateLatency<T>(data: T, delayMs: number = 350): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(data), delayMs));
}
